language: csharp

dotnet: 3.1.101

install:
  # workaround for missing .net 4.6.1 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api/

script:
  - dotnet tool restore
  - dotnet pack -v n
  - dotnet test -v n -p:UnstableTests=$UnstableTests

mono:
- 6.8.0

matrix:
  include:
    - os: linux
      dist: xenial
      env: UnstableTests=false
    - os: osx
      osx_image: xcode9
      env: UnstableTests=false
    - os: linux
      dist: xenial
      env: UnstableTests=true
    - os: osx
      osx_image: xcode9
      env: UnstableTests=true
    - os: linux
      dist: xenial  
      env: UnstableTests=false
    - os: osx
      osx_image: xcode9
      env: UnstableTests=false
  allow_failures:
    # unstable tests may fail
    - env: UnstableTests=true
    - dist: xenial
      