language: csharp

dotnet: 3.1.101

install:
  # workaround for missing .net 4.6.1 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api/

script:
  - dotnet tool restore
  - dotnet pack -v n
  - dotnet test -v n -p:UnstableTests=$UnstableTests

mono:
- 6.8.0

# one build triggered for each of these
os:
- linux
- osx

# one build triggered for each of these
env:
- UnstableTests=false
- UnstableTests=true

# target the dist/osx_image based on `os`, regardless of other settings
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.2
  allow_failures:
    # unstable tests may fail
    - env: UnstableTests=true