# to reenable AZDO builds, rename this file to 'azure-pipelines.yml' and commit.
# these builds are close to complete, but:
# * on windows the `MSBuild.exe` binary can't be located so the tests that crack projects using it fail
# * on linux/osx the reference assemblies for net461 can't be located at runtime.
#    * I've tried setting the FrameworkPathOverride and that hasn't done the job.
#    * might be able to do something with the nuget package for the ref assemblies?
name: $(Rev:r)

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-18.04'
    mac:
      imageName: 'macos-10.15'
    windows:
      imageName: 'windows-2019'
    

pool:
  vmImage: $(imageName)

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core Sdk from global.json'
  inputs:
    useGlobalJson: true
- task: UseDotNet@2
  displayName: 'Add .Net Core SDK 2.1.x for test projects'
  inputs:
    version: '2.1.x'
- script: dotnet tool restore
  displayName: Install Tools
- script: dotnet pack -v n
  displayName: Build packages
- script: dotnet test -v n -p:UnstableTests=false
  displayName: Run Tests
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '*.xml'
    searchFolder: 'bin/test_results'
    publishRunAttachments: true
  condition: always()
  continueOnError: true